module.exports = {
    devServer: {
      port: 8081,
      open: true
    },
    lintOnSave: false,
    publicPath: "./",
    outputDir: "dist",
    assetsDir: "static",//Set the directory where the static resources (js, css, img, fonts) generated by the package will be placed.
    indexPath: 'index.html'//Used to set the storage location of the index.html file generated by the package
  }